version: "3.8"

services:
  omotes-rest:
      image: omotes-rest-dev
      build:
        context: ..
        dockerfile: omotes-rest/dev.Dockerfile
  rest_postgres_db:
    ports:
      - "${POSTGRES_PORT}:5432"
