version: "3.8"

networks:
  omotes:

volumes:
  db-data:

services:
  omotes-rest:
      build:
        context: ..
        dockerfile: omotes-rest/dev.Dockerfile
  rest_postgres_db:
    ports:
      - "${POSTGRES_PORT}:5432"
