version: "3.8"

services:
  postgis:
    image: postgis/postgis:latest
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${POSTGIS_DATABASE_NAME}
      POSTGRES_USER: ${POSTGIS_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGIS_ROOT_PASSWORD}
    ports:
      - "9232:5432"
    volumes:
      - "./postgres_db/initdb.d/:/docker-entrypoint-initdb.d"
      - "postgis-data:/var/lib/postgresql/data"
    restart: unless-stopped

#  pgadminer:
#    image: adminer
#    environment:
#      - ADMINER_DESIGN=lucas-sandery
#      - ADMINER_DEFAULT_SERVER=postgis
#    ports:
#      - "9280:8080"

volumes:
  postgis-data:
