version: "3.8"

networks:
  computation-engine_omotes:

volumes:
  db-data:

services:
  rest_postgres_db: &rest_postgres_db
    image: postgres:15.4
    restart: unless-stopped
    volumes:
      - "db-data:/var/lib/postgresql/data/"
    networks:
      - computation-engine_omotes
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: omotes
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_ROOT_USER}", "-d", "omotes" ]
      interval: 5s
      timeout: 5s
      retries: 10
#    ports:
#      - "${POSTGRESQL_PORT}:5432"

  # Skipped in 'docker-compose up', only used to develop database revisions.
  rest_postgres_db_dev:
    <<: *rest_postgres_db
    ports:
      - "${POSTGRES_DEV_PORT}:5432"
    profiles:
      - manual_dev

  # Skipped in 'docker-compose up', only used in 'setup.sh'
  rest_postgres_db_upgrade:
    build: postgres_db_upgrade
    networks:
      - computation-engine_omotes
    environment:
      POSTGRES_ROOT_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_HOST: rest_postgres_db
      POSTGRES_PORT: 5432
    depends_on:
      rest_postgres_db:
        condition: service_healthy
    profiles:
      - manual_setup
